name: Terraform Apply on Master

# This would be the preffered way, if master branch protection was enabled
# on:
#   push:
#     branches:
#       - master

on:
  pull_request:
    branches:
      - master
    types: [closed]

permissions:
  # This is needed for aws-actions/configure-aws-credentials to work
  id-token: write
  contents: read

concurrency:
  group: terraform-github-actions

env:
  ROLE_TO_ASSUME: <GITHUB_ROLE_IN_MANAGEMENT_ACCOUNT_FOR_TERRAFORM_REPO>
  AWS_REGION: <YOUR_AWS_REGION>

jobs:
  terraform-validate-and-apply:
    if: ${{ github.event.pull_request.merged }} # Once again this is a workaround to trigger the job only after PR merge, rather than direct push to master
    runs-on: [ubuntu-latest]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Check Formatting
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -no-color

        # To catch accidentally deleting or changing remote backend
        # If state is not present, this will fail
      - name: Terraform Verify State
        id: verify-state
        run: terraform state list -no-color

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color -input=false

      - name: Terraform Apply
        id: apply
        run: terraform apply  -no-color -input=false -auto-approve
